name    'fortin/pptpd'
version '0.1.0'
source 'https://github.com/shaftoe/puppet-pptpd'
author 'Alexander Fortin'
license 'Apache License, Version 2.0'
summary 'Pptp server'
description 'Pptp server for Debian distributions'
project_page 'https://github.com/shaftoe/puppet-pptpd'
