name    'shaftoe/pptpd'
version '0.0.1'
source 'UNKNOWN'
author 'Alexander Fortin'
license 'Apache License, Version 2.0'
summary 'Pptp server'
description 'Pptp server'
project_page 'https://github.com/shaftoe/puppet-pptpd'
